### PR TITLE
Shorter "going to sleep" message after the fifth time

### PR DESCRIPTION
**Pull request by boot-ini**
The default message when Mycroft is going to sleep takes quite a while to speak, which is frustrating when you're trying to get Mycroft to be quiet when you're watching TV or having a conversation. This change tweaks it so after the fifth time Mycroft has explained about waking up he'll just say "Okay" when you tell him to go to sleep.

### CODE REVIEW

**Comment by forslund** [comment]
Hi @StefanBCN,

I've thought about something like this as well but never gotten round to adding it.

There's a couple of small things I's like to modify here but the majority looked good. Why did you close it?

**Comment by boot-ini** [comment]
Heya @forslund 

I closed it for no good reason, really - I thought my changes might've been a bit presumptuous and bottled it. Glad to hear the changes sound mostly good. Can I reopen it from here or is it something you have to do? The button is greyed out on my end.

**Comment by forslund** [comment]
Hmm, mine is also grayed out. Maybe you can submit it again?

**Comment by boot-ini** [comment]
Done, apologies for the kerfuffle

**Pull request closed without merging**
